### PR TITLE
Always reset assertion count

### LINKED ISSUE #4: Test failure causes assertion count to fail on subsequent tests
### Package version

v3.0.3

### Describe the bug

When using `expect.assertions(number)`, and when a test fails or throws an exception, then the assertion count is not reset before moving onto the next test, which causes that test to fail because of an incorrect number of assertions.

https://github.com/japa/expect/blob/4797c9bb9b68e0956f92016e265bbda336ee9f3b/index.ts#L21-L30

Inside `jestExpect.extractExpectedAssertionsErrors()` is where the assertion count is reset. But you only call this if the test doesn't throw any exceptions.

### Reproduction repo

_No response_

### PR DESCRIPTION
**Pull request by brettwillis**
### 🔗 Linked issue

Fixes #4 

### ❓ Type of change

- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

See #4.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] ~I have updated the documentation accordingly.~

### CODE REVIEW

File: index.ts [hunk 1]
```diff
@@ -19,13 +19,14 @@ export function expect(): PluginFn {
...
+      // resets the assertion count and otherwise the assertion count will be
+      // carried into a subsequent test
+      const jestErrors = jestExpect.extractExpectedAssertionsErrors();
 
-      const jestErrors = jestExpect.extractExpectedAssertionsErrors()
-      if (jestErrors.length) {
-        throw jestErrors[0].error
+      // Throw assertion count errors only if the test otherwise passed
+      if (jestErrors.length && !hasError) {
+        throw jestErrors[0].error;
```
Comment (thetutlage) [inline index.ts]: Nit pick. Can you please remove the semicolon or better just run `npm run format` to reformat all the files.

**Comment by thetutlage** [comment]
Thanks 👍
